Mini-Challenge 1
Boomerang24/react-certification-2021 pull request #1
Opened 2021-07-25 23:34 UTC by Boomerang24

NavBar creation
Cards are added
Fetch information from Mockfile
Formatted cards

2021-07-27 03:17 UTC, omarscd commented on package.json
> -    "eslint-plugin-react-hooks": "^4.1.0",
estás seguro que quieres deshacerte de todo esto?

2021-07-27 03:17 UTC, omarscd commented on package.json
> +      "react-app/jest"
sabes qué reglas incluyen estas configuraciones?

2021-07-27 03:17 UTC, omarscd commented on src/components/NavBar/NavBar.js
> +}
Generalmente se hace un salto de línea al final de los archivos, aquí te dejo un link con unas cuantas razones para hacerlo https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

2021-07-27 03:17 UTC, omarscd commented on src/components/Switch/Switch.js
> +    checkedB: true,
Te recomendaría tener nombres más descriptivos para tus variables; en lugar de A y B, puedes ponerle el nombre de lo que representan, por ejemplo `checkedDarkTheme` o algo que haga sentido para ti

2021-07-27 03:17 UTC, omarscd commented on src/components/NavBar/NavBar.js
> +    }
responsividad 💯 💅🏼

2021-07-27 03:17 UTC, omarscd commented on package.json
> +    "test": "react-scripts test --coverage",
si vas a usar TDD, probablemente prefieras también tener un script incluyendo la bandera `--watch`
```
```

2021-07-27 03:26 UTC, omarscd requested changes
Buen trabajo!

2021-07-27 03:26 UTC, omarscd commented on src/tests/components/Navbar/NavBar.test.js
> +        )
He notado que en algunas líneas falta el `;`, en js no es obligatorio ponerlo, pero sí te recomendaría apegarte a la decisión de usarlo siempre o no usarlo nunca.
También correr el linter podría ayudarte a no tener que preocuparte por hacer esto manualmente.

2021-07-27 03:26 UTC, omarscd commented on src/components/Grid/GridItem.js
> +            <StyledImage src={thumbnail} role="img" alt="SoyUnaImagen" />
Por accesibilidad(entre otras cosas), hay que procurar poner textos más descriptivos en el atributo `alt`
https://moz.com/learn/seo/alt-text

2021-07-27 23:13 UTC, Boomerang24 commented
Buen dia Omar,

Muchas gracias por tus comentarios, lo tomare en cuenta y realizare estos cambios para mi siguiente entregable.

Excelente dia!

2021-07-27 23:13 UTC, closed without merging

2021-07-27 23:27 UTC, Boomerang24 commented on package.json
> +      "react-app/jest"
Honestamente desconozco que configuraciones tienen, supongo que fueron creadas por medio del npx create-react-app.

Agradecería mucho pudieras compartirme un recurso para estudiar/aprender al respecto

2021-07-27 23:42 UTC, Boomerang24 commented on package.json
> -    "eslint-plugin-react-hooks": "^4.1.0",
Gracias por mencionarlo, ya lo agregue nuevamente a mi package.json

2021-07-28 01:15 UTC, omarscd commented on package.json
> +      "react-app/jest"
Claro, en esta página te dice cuales son las reglas que incluye https://www.npmjs.com/package/eslint-config-react-app, puedes notar que es como tú mencionas, CRA ya las incluye por default y no es necesario instalarlas por ti mismo.
En la parte que hace el `npm install --save-dev ...` puedes ver también la lista de plugins que te incluye, si quieres saber qué hace cada uno, en esa misma página puedes buscarlos para ver su documentación.

2021-07-29 04:31 UTC, Boomerang24 commented on package.json
> +      "react-app/jest"
Muchas gracias por pasarme esta información Omar!